### PR TITLE
Add transactions in batch through text

### LINKED ISSUE #12: Add transactions in batch through text file
Right now, all transactions are added individually. I think it is a good idea for the user to be able to add many of them at the same time through a text file.

A scenario this can be useful is that the user does not have a network connection at the moment. Writing all transactions down on a file and process them at the same time would help.

The new command syntax can be:
```
budget add --file-path ~/path/to/text/file.txt
```

File format can be:
```
# Text file can have comments and should be ignored
expense: 900, Rent, House
expense: Aug 8, 60, Gas, Other
income: Oct 11, 2000, Paycheck, Paycheck
income: 150, Paycheck, Bonus
```

How do you think?

### PR DESCRIPTION
**Pull request by Grommers00**
Closes #12

I created a new command for parsing a file. It then goes through the loop of a file and will sequentially add them to your spreadsheets.  It takes into consideration for comments in the code as well, so you as long as you # the beginning of the line in the text file it would be able to do this.

To use this the command:
`budget insert \PATH\TO\FILE`

### CODE REVIEW

**Comment by utkuufuk** [comment]
@Grommers00 Good work so far 👍 

Here's what I did:
 * Added error handling so that any incorrect commands in the file won't prevent the following commands from being executed.
 * Removed capability to add comments in transaction file, simply because there's no need.
 * Polished styling & renamed some variables.

There's a problem though; I can only give absolute paths as the argument. I want to be able to pass relative paths too. We can merge this after that is taken care of.

**Comment by Grommers00** [comment]
Ah - Yeah, I ran into that issue at the beginning, and I found it would work in the .budget-cli folder, as a relative. I'm open to suggestions - but that was the CWD when I checked.

**Comment by utkuufuk** [comment]
@Grommers00 Before reading the file, you have to temporarily change the CWD as the directory where the user is currently running the `budget insert` command. 

I don't know how to do it, but it shouldn't be difficult.

**Comment by utkuufuk** [comment]
@Grommers00 Nevermind, I just fixed it. It turns out I forgot to restore the CWD after building the sheet service.

**Review by utkuufuk — APPROVED** [review]

**Pull request merged**
